# Generated by Django 5.2.4 on 2025-08-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meican", "0002_meicanuser_created_at_meicanuser_is_active_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderrecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="orderrecord",
            name="meal_period",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="orderrecord",
            unique_together={("user", "order_date", "meal_period")},
        ),
    ]
