# Generated by Django 5.2.4 on 2025-08-01 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meican", "0003_alter_orderrecord_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderrecord",
            name="tab_uid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="TabStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tab_uid", models.CharField(max_length=100)),
                ("tab_title", models.CharField(max_length=200)),
                ("target_time", models.DateTimeField()),
                ("status", models.CharField(max_length=20)),
                ("order_date", models.DateField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tab_statuses",
                        to="meican.meicanuser",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "order_date"],
                        name="meican_tabs_user_id_2e68f8_idx",
                    ),
                    models.Index(
                        fields=["order_date", "status"],
                        name="meican_tabs_order_d_4c0dc3_idx",
                    ),
                ],
                "unique_together": {("user", "tab_uid", "order_date")},
            },
        ),
    ]
